---
    - hosts: linux
      gather_facts: false

      tasks:
      - name: install nginx
        package:
          name:
            - nginx
          state: latest
        become: yes

      - name: copy index.html
        copy:
          src: index.html
          dest: /usr/share/nginx/html/index.html
        become: yes

      - name: start nginx service
        service:
            name: nginx
            state: started
            enabled: yes
        become: yes
